apiVersion: v1
kind: Service
metadata:
  name: beautiful-rajesh-d234d024ad-srv
  namespace: keda-test
spec:
  selector:
    app: beautiful-rajesh-d234d024ad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP
